/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bruno.frame;

import br.com.bruno.objeto.Aluno;
import br.com.bruno.objeto.Nota;
import br.com.bruno.objeto.tipoAvaliacao;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class Principal extends javax.swing.JFrame {
   
    /**
     * Creates new form Principal
     */
    
    Aluno a; 
    
    public Principal() {

        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCalculo = new javax.swing.JLabel();
        jPAluno = new javax.swing.JPanel();
        jLAluno = new javax.swing.JLabel();
        jLMatricula = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jBCadastrarAluno = new javax.swing.JButton();
        jTMatriculaAluno = new javax.swing.JTextField();
        jTNomeAluno = new javax.swing.JTextField();
        jPNotas = new javax.swing.JPanel();
        jLNotas = new javax.swing.JLabel();
        jLN1 = new javax.swing.JLabel();
        jLN2 = new javax.swing.JLabel();
        jLN3 = new javax.swing.JLabel();
        jLN4 = new javax.swing.JLabel();
        jTN1 = new javax.swing.JTextField();
        jTN2 = new javax.swing.JTextField();
        jTN3 = new javax.swing.JTextField();
        jTN4 = new javax.swing.JTextField();
        jBCalcular = new javax.swing.JButton();
        jLNomeDisciplina = new javax.swing.JLabel();
        jTNomeDisciplina = new javax.swing.JTextField();
        jCTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLCalculo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLCalculo.setForeground(new java.awt.Color(255, 0, 51));
        jLCalculo.setText(" Calculo de média");

        jPAluno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLAluno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLAluno.setText("Aluno");

        jLMatricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLMatricula.setText("Matrícula");

        jLNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLNome.setText("Nome");

        jBCadastrarAluno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCadastrarAluno.setText("Cadastrar");
        jBCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAlunoLayout = new javax.swing.GroupLayout(jPAluno);
        jPAluno.setLayout(jPAlunoLayout);
        jPAlunoLayout.setHorizontalGroup(
            jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAlunoLayout.createSequentialGroup()
                .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPAlunoLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLNome)
                                .addComponent(jLMatricula))
                            .addGap(49, 49, 49))
                        .addGroup(jPAlunoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTMatriculaAluno)
                                .addComponent(jTNomeAluno))))
                    .addGroup(jPAlunoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLAluno))
                    .addGroup(jPAlunoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jBCadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPAlunoLayout.setVerticalGroup(
            jPAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAluno)
                .addGap(18, 18, 18)
                .addComponent(jLMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBCadastrarAluno)
                .addGap(27, 27, 27))
        );

        jPNotas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLNotas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLNotas.setText("Notas");

        jLN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLN1.setText("N1");

        jLN2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLN2.setText("N1");

        jLN3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLN3.setText("N1");

        jLN4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLN4.setText("N1");

        jBCalcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jLNomeDisciplina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLNomeDisciplina.setText("Nome da Disciplina");

        jTNomeDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeDisciplinaActionPerformed(evt);
            }
        });

        jCTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma das opções", "Prova", "Trabalho", "Seminário" }));
        jCTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPNotasLayout = new javax.swing.GroupLayout(jPNotas);
        jPNotas.setLayout(jPNotasLayout);
        jPNotasLayout.setHorizontalGroup(
            jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNotasLayout.createSequentialGroup()
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jBCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPNotasLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLNotas))
                            .addGroup(jPNotasLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPNotasLayout.createSequentialGroup()
                                        .addComponent(jLN2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPNotasLayout.createSequentialGroup()
                                        .addComponent(jLN1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTN1))
                                    .addGroup(jPNotasLayout.createSequentialGroup()
                                        .addComponent(jLN4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTN4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPNotasLayout.createSequentialGroup()
                                        .addComponent(jLN3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTN3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPNotasLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLNomeDisciplina))
                            .addGroup(jPNotasLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jTNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNotasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPNotasLayout.setVerticalGroup(
            jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNotasLayout.createSequentialGroup()
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNotas)
                            .addComponent(jLNomeDisciplina))
                        .addGap(41, 41, 41)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLN1)
                            .addComponent(jTN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLN2)
                            .addComponent(jTN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPNotasLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jCTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLN3)
                    .addComponent(jTN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLN4)
                    .addComponent(jTN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCalcular)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCalculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarAlunoActionPerformed

        
        String nomeAluno = jTNomeAluno.getText();
        int matriculaAluno = 0;
try{
        matriculaAluno = Integer.parseInt(jTMatriculaAluno.getText());
}catch(NumberFormatException nfe){
    JOptionPane.showMessageDialog(this, "Você digitou um caracter errado" + nfe);
    throw new RuntimeException();
}
    Aluno k = new Aluno(nomeAluno, matriculaAluno);
    JOptionPane.showMessageDialog(this, k.toString());
    

    }//GEN-LAST:event_jBCadastrarAlunoActionPerformed

    private void jTNomeDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeDisciplinaActionPerformed

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        
        tipoAvaliacao tipo = null;
        Aluno a = new Aluno(jTNomeAluno.getText(), Integer.parseInt(jTMatriculaAluno.getText()));
        switch(jCTipo.getSelectedIndex()){
            case 0:{
                tipo = tipoAvaliacao.Prova;
                break;
            }
            case 1: {
                tipo = tipoAvaliacao.Trabalho;
                break;
            }
            case 2: {
                tipo = tipoAvaliacao.Seminario;
                break;
            }
        }
        try{
            a.getNota().add(new Nota(jTNomeDisciplina.getText(), tipo, Float.parseFloat(jTN1.getText() )));
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Você digitou um caracter inválido!!" +nfe);
            throw new RuntimeException();
        }
        
         try{
            a.getNota().add(new Nota(jTNomeDisciplina.getText(), tipo, Float.parseFloat(jTN2.getText() )));
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Você digitou um caracter inválido!!" +nfe);
            throw new RuntimeException();
        }
         
          try{
            a.getNota().add(new Nota(jTNomeDisciplina.getText(), tipo, Float.parseFloat(jTN3.getText() )));
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Você digitou um caracter inválido!!" +nfe);
            throw new RuntimeException();
        }
          
           try{
            a.getNota().add(new Nota(jTNomeDisciplina.getText(), tipo, Float.parseFloat(jTN4.getText() )));
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "Você digitou um caracter inválido!!" +nfe);
            throw new RuntimeException();
        }
      JOptionPane.showMessageDialog(null, a.toString()
              + "\n" + " media: " + a.calcularMedia());
     
    }//GEN-LAST:event_jBCalcularActionPerformed

    private void jCTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTipoActionPerformed

      new javax.swing.DefaultComboBoxModel(tipoAvaliacao.values());
        
    }//GEN-LAST:event_jCTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarAluno;
    private javax.swing.JButton jBCalcular;
    private javax.swing.JComboBox<String> jCTipo;
    private javax.swing.JLabel jLAluno;
    private javax.swing.JLabel jLCalculo;
    private javax.swing.JLabel jLMatricula;
    private javax.swing.JLabel jLN1;
    private javax.swing.JLabel jLN2;
    private javax.swing.JLabel jLN3;
    private javax.swing.JLabel jLN4;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLNomeDisciplina;
    private javax.swing.JLabel jLNotas;
    private javax.swing.JPanel jPAluno;
    private javax.swing.JPanel jPNotas;
    private javax.swing.JTextField jTMatriculaAluno;
    private javax.swing.JTextField jTN1;
    private javax.swing.JTextField jTN2;
    private javax.swing.JTextField jTN3;
    private javax.swing.JTextField jTN4;
    private javax.swing.JTextField jTNomeAluno;
    private javax.swing.JTextField jTNomeDisciplina;
    // End of variables declaration//GEN-END:variables
}
